steps:
  - label: Build
    command: |
      echo "--- Build test container"
      script/build

      echo "--- Push test container"
      script/push
    env:
      BUILD: test

  - wait

  - label: Lint
    command: |
      set +e
      docker run nx584-test:${BUILDKITE_BUILD_NUMBER} script/lint
      EXIT_STATUS="$$?"
      buildkite-agent meta-data set "lint-exit-status" $$EXIT_STATUS
      set -e
      exit $$EXIT_STATUS

  - label: Test
    command: |
      set +e
      docker run nx584-test:${BUILDKITE_BUILD_NUMBER} script/test
      EXIT_STATUS="$$?"
      buildkite-agent meta-data set "test-exit-status" $$EXIT_STATUS
      set -e
      exit $$EXIT_STATUS

  - wait: ~
    continue_on_failure: true

  - label: Push
    command: |
      echo "--- Build production container"
      script/build

      echo "--- Push production container"
      script/push
    env:
      BUILD: production
